### ISSUE TITLE
Failed to load the behat-tools package

### ISSUE THREAD

**Issue by rafaelnery** [rafaelnery/behat-tools#1]
Just Open Atom

**Atom Version**: 1.8.0
**System**: Ubuntu 16.04
**Thrown From**: [behat-tools](https://github.com/rafaelnery/behat-tools) package, v1.0.0
### Stack Trace

Failed to load the behat-tools package

```
At Unexpected token }

SyntaxError: Unexpected token }
    at Object.parse (native)
    at parseObject (/opt/atom/resources/app.asar/node_modules/season/lib/cson.js:54:19)
    at parseContentsSync (/opt/atom/resources/app.asar/node_modules/season/lib/cson.js:68:16)
    at Object.module.exports.readFileSync (/opt/atom/resources/app.asar/node_modules/season/lib/cson.js:170:14)
    at /opt/atom/resources/app.asar/src/package.js:403:43
    at Array.map (native)
    at Package.module.exports.Package.loadMenus (/opt/atom/resources/app.asar/src/package.js:401:42)
    at /opt/atom/resources/app.asar/src/package.js:111:19
    at Package.module.exports.Package.measure (/opt/atom/resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/opt/atom/resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/opt/atom/resources/app.asar/src/package-manager.js:457:14)
    at /opt/atom/resources/app.asar/src/package-manager.js:402:19
    at Config.module.exports.Config.transact (/opt/atom/resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/opt/atom/resources/app.asar/src/package-manager.js:397:19)
    at /opt/atom/resources/app.asar/src/atom-environment.js:743:28
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "project-plus",
      "file-type-icons"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "CVS",
      ".idea",
      "tags",
      ".cvsignore"
    ],
    "themes": [
      "one-dark-ui",
      "atom-material-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-autocomplete-php, v0.18.9
atom-material-syntax, v0.4.6
docblockr, v0.7.3
file-icons, v1.7.15
language-gherkin-pt, v1.0.1
linter, v1.11.14
linter-php, v1.2.0
minimap, v4.24.6
project-manager, v2.9.7
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by rafaelnery** [comment]
Fixed in version v2
